baseurl: /
account: palexand
github: https://github.com/palexand
title: Dr. Perry Alexander
subtitle: The University of Kansas
ohrs: 10:45-12:00 TR
markdown: kramdown
name: WPA
description: Perry Alexander's Website
url: http://palexand.github.io
