baseurl: http://perry.alexander.name
account: palexand
github: https://github.com/palexand
title: Dr. Perry Alexander
subtitle: The University of Kansas
ohrs: No summer office hours
markdown: kramdown
name: WPA
description: Perry Alexander's Website
url: http://palexand.github.io
